# Shared — works on macOS and Linux Homebrew.
# GUI apps with hotkeys are managed via apps.json + install.sh, not here.

brew "git"
brew "node"
brew "java"
brew "python"
brew "awscli"
brew "go"
brew "bat"
brew "eza"
brew "fd"
brew "fzf"
brew "neovim"
brew "pyenv"
brew "rbenv"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-vi-mode"
brew "thefuck"
brew "gnupg"
brew "gh"
brew "jq"
brew "lazygit"
