#!/usr/bin/env bash
# Generates .skhdrc from apps.json.
# Run via install.sh or: bash scripts/gen-skhdrc.sh > .skhdrc

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="$SCRIPT_DIR/../apps.json"

cat <<'HEADER'
# Generated by scripts/gen-skhdrc.sh — do not edit directly.
# To change bindings, edit apps.json and re-run install.sh.
HEADER

jq -r '.[] | "rshift - \(.hotkey) : open -a \"\(.darwin_app)\""' "$MANIFEST"
