#!/usr/bin/env bash
# Generates hotkeys.ahk from apps.json.
# Run via install.sh or: bash scripts/gen-hotkeys.ahk.sh > hotkeys.ahk

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="$SCRIPT_DIR/../apps.json"

cat <<'HEADER'
; Generated by scripts/gen-hotkeys.ahk.sh — do not edit directly.
; To change bindings, edit apps.json and re-run install.sh.
#Requires AutoHotkey v2.0
#SingleInstance Force

ActivateOrRun(winTitle, exeName) {
    if WinExist(winTitle) {
        WinActivate
    } else {
        Run exeName
    }
}

HEADER

# Skip entries without a win_exe (optional/internal apps with no Windows package).
jq -r '.[] | select(.win_exe != null) | "RShift & \(.hotkey)::\tActivateOrRun(\"\(.win_title)\", \"\(.win_exe)\")"' "$MANIFEST"
