#!/usr/bin/env bash
# Generates .skhdrc from apps.json.
# Run via install.sh or: bash scripts/gen-skhdrc.sh > .skhdrc

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="$SCRIPT_DIR/../apps.json"

cat <<'HEADER'
# Generated by scripts/gen-skhdrc.sh — do not edit directly.
# To change bindings, edit apps.json and re-run install.sh.
HEADER

jq -r '
  .[]
  | select(.darwin_app != null)
  | [
      .hotkey,
      .darwin_app,
      (.darwin_process // .darwin_app),
      (.darwin_ensure_window // false)
    ]
  | @tsv
' "$MANIFEST" | while IFS=$'\t' read -r hotkey app process ensure_window; do
  if [[ "$ensure_window" == "true" ]]; then
    printf "rshift - %s : osascript -e 'tell application \"%s\" to activate' -e 'tell application \"System Events\" to tell process \"%s\" to if (count of windows) = 0 then keystroke \"n\" using command down'\n" "$hotkey" "$app" "$process"
  else
    printf "rshift - %s : if pgrep \"%s\" > /dev/null; then osascript -e 'tell application \"%s\" to activate'; else open -a \"%s\"; fi\n" "$hotkey" "$process" "$app" "$app"
  fi
done
