#!/usr/bin/env luajit
-- Compiles apps.lua into per-OS launcher config and package lists.
--   luajit gen.lua skhd    -> .skhdrc lines           (macOS / skhd)
--   luajit gen.lua ahk     -> hotkeys.ahk             (Windows / AutoHotkey v2)
--   luajit gen.lua casks   -> brew cask names, one per line
--   luajit gen.lua winget  -> winget ids, one per line
-- Runs under luajit or lua5.x (5.1-compatible). Edit apps.lua, not the output.

local here = arg[0]:match("^(.*[/\\])") or "./"
local apps = dofile(here .. "../apps.lua")

local mode = arg[1]
local out = {}

if mode == "skhd" then
  out[#out + 1] = "# Generated by scripts/gen.lua — do not edit directly."
  out[#out + 1] = "# To change bindings, edit apps.lua and re-run install.sh."
  for _, a in ipairs(apps) do
    if a.darwin_app then
      local app = a.darwin_app
      local process = a.darwin_process or a.darwin_app
      local new_window = a.darwin_new_window or "keystroke"
      if a.darwin_ensure_window then
        if new_window == "make_new_window" then
          out[#out + 1] = ("rshift - %s : osascript -e 'tell application \"%s\" to activate' -e 'if (count of windows of application \"%s\") = 0 then tell application \"%s\" to make new window'")
            :format(a.hotkey, app, app, app)
        elseif new_window == "reopen" then
          out[#out + 1] = ("rshift - %s : osascript -e 'tell application \"%s\" to reopen' -e 'tell application \"%s\" to activate'")
            :format(a.hotkey, app, app)
        else
          out[#out + 1] = ("rshift - %s : osascript -e 'tell application \"%s\" to activate' -e 'delay 0.2' -e 'tell application \"System Events\" to tell process \"%s\" to if (count of windows) = 0 then keystroke \"n\" using command down'")
            :format(a.hotkey, app, process)
        end
      else
        out[#out + 1] = ("rshift - %s : if pgrep \"%s\" > /dev/null; then osascript -e 'tell application \"%s\" to activate'; else open -a \"%s\"; fi")
          :format(a.hotkey, process, app, app)
      end
    end
  end

elseif mode == "ahk" then
  out[#out + 1] = "; Generated by scripts/gen.lua — do not edit directly."
  out[#out + 1] = "; To change bindings, edit apps.lua and re-run install.sh."
  out[#out + 1] = "#Requires AutoHotkey v2.0"
  out[#out + 1] = "#SingleInstance Force"
  out[#out + 1] = ""
  out[#out + 1] = "ActivateOrRun(winTitle, exeName) {"
  out[#out + 1] = "    if WinExist(winTitle) {"
  out[#out + 1] = "        WinActivate"
  out[#out + 1] = "    } else {"
  out[#out + 1] = "        Run exeName"
  out[#out + 1] = "    }"
  out[#out + 1] = "}"
  out[#out + 1] = ""
  for _, a in ipairs(apps) do
    if a.win_exe then
      -- AHK v2 escapes a literal quote by doubling it.
      local title = (a.win_title or ""):gsub('"', '""')
      local exe = a.win_exe:gsub('"', '""')
      out[#out + 1] = ("RShift & %s::\tActivateOrRun(\"%s\", \"%s\")"):format(a.hotkey, title, exe)
    end
  end

elseif mode == "casks" then
  for _, a in ipairs(apps) do
    if a.brew_cask then out[#out + 1] = a.brew_cask end
  end

elseif mode == "winget" then
  for _, a in ipairs(apps) do
    if a.winget_id then out[#out + 1] = a.winget_id end
  end

else
  io.stderr:write("usage: gen.lua {skhd|ahk|casks|winget}\n")
  os.exit(1)
end

io.write(table.concat(out, "\n") .. "\n")
