#!/usr/bin/env luajit
-- Compiles apps.lua into per-OS launcher config and package lists.
--   luajit gen.lua skhd    -> .skhdrc lines           (macOS / skhd)
--   luajit gen.lua ahk     -> hotkeys.ahk             (Windows / AutoHotkey v2)
--   luajit gen.lua casks   -> brew cask names, one per line
--   luajit gen.lua winget  -> winget ids, one per line
-- Runs under luajit or lua5.x (5.1-compatible). Edit apps.lua, not the output.

local here = arg[0]:match("^(.*[/\\])") or "./"
local apps = dofile(here .. "../apps.lua")

local mode = arg[1]
local out = {}

if mode == "skhd" then
  out[#out + 1] = "# Generated by scripts/gen.lua — do not edit directly."
  out[#out + 1] = "# To change bindings, edit apps.lua and re-run install.sh."
  for _, a in ipairs(apps) do
    if a.darwin_app then
      local app = a.darwin_app
      local process = a.darwin_process or a.darwin_app
      local new_window = a.darwin_new_window or "keystroke"
      if a.darwin_ensure_window then
        if new_window == "make_new_window" then
          out[#out + 1] = ("rshift - %s : osascript -e 'tell application \"%s\" to activate' -e 'if (count of windows of application \"%s\") = 0 then tell application \"%s\" to make new window'")
            :format(a.hotkey, app, app, app)
        elseif new_window == "reopen" then
          out[#out + 1] = ("rshift - %s : osascript -e 'tell application \"%s\" to reopen' -e 'tell application \"%s\" to activate'")
            :format(a.hotkey, app, app)
        else
          out[#out + 1] = ("rshift - %s : osascript -e 'tell application \"%s\" to activate' -e 'delay 0.2' -e 'tell application \"System Events\" to tell process \"%s\" to if (count of windows) = 0 then keystroke \"n\" using command down'")
            :format(a.hotkey, app, process)
        end
      else
        -- Running: `reopen` restores a window when the app is open but has
        -- none (tray/menu-bar apps like Slack, Discord, 1Password), then
        -- `activate` focuses it. Not running: `open -a` launches it.
        out[#out + 1] = ("rshift - %s : if pgrep \"%s\" > /dev/null; then osascript -e 'tell application \"%s\" to reopen' -e 'tell application \"%s\" to activate'; else open -a \"%s\"; fi")
          :format(a.hotkey, process, app, app, app)
      end
    end
  end

elseif mode == "ahk" then
  out[#out + 1] = "; Generated by scripts/gen.lua — do not edit directly."
  out[#out + 1] = "; To change bindings, edit apps.lua and re-run install.sh."
  out[#out + 1] = "; NOTE: Windows behavior is a best-effort STUB and has not been tested on"
  out[#out + 1] = "; a Windows host. Launch prefers AUMID when set (see apps.lua) and window-"
  out[#out + 1] = "; ensure is a no-op placeholder. Verify before relying on it."
  out[#out + 1] = "#Requires AutoHotkey v2.0"
  out[#out + 1] = "#SingleInstance Force"
  out[#out + 1] = ""
  out[#out + 1] = "; Launch via AppsFolder (AUMID) when known — resolves per-user and Store"
  out[#out + 1] = "; installs that a bare exe name on PATH would miss. Falls back to the raw"
  out[#out + 1] = "; exe (browsers register App Paths and resolve; most Electron apps do not)."
  out[#out + 1] = "LaunchApp(aumid, exeName) {"
  out[#out + 1] = "    if (aumid != \"\") {"
  out[#out + 1] = "        Run('explorer.exe \"shell:AppsFolder\\' . aumid . '\"')"
  out[#out + 1] = "    } else {"
  out[#out + 1] = "        Run(exeName)"
  out[#out + 1] = "    }"
  out[#out + 1] = "}"
  out[#out + 1] = ""
  out[#out + 1] = "ActivateOrRun(winTitle, aumid, exeName) {"
  out[#out + 1] = "    if WinExist(winTitle) {"
  out[#out + 1] = "        WinActivate"
  out[#out + 1] = "    } else {"
  out[#out + 1] = "        LaunchApp(aumid, exeName)"
  out[#out + 1] = "    }"
  out[#out + 1] = "}"
  out[#out + 1] = ""
  out[#out + 1] = "; STUB: window-ensure is unimplemented on Windows (untested — no Windows"
  out[#out + 1] = "; host). On macOS this forces a new/reopened window when the app has none;"
  out[#out + 1] = "; here it is a no-op after activation. TODO: detect zero windows and send"
  out[#out + 1] = "; the app's new-window shortcut (usually ^n)."
  out[#out + 1] = "EnsureWindow(winTitle) {"
  out[#out + 1] = "    ; intentionally empty — see TODO above"
  out[#out + 1] = "}"
  out[#out + 1] = ""
  for _, a in ipairs(apps) do
    -- Include an app on Windows if it has any launch handle (exe or AUMID).
    if a.win_exe or a.win_aumid then
      -- AHK v2 escapes a literal quote by doubling it; backslash is literal.
      local title = (a.win_title or ""):gsub('"', '""')
      local exe = (a.win_exe or ""):gsub('"', '""')
      local aumid = (a.win_aumid or ""):gsub('"', '""')
      if a.darwin_ensure_window then
        out[#out + 1] = ("RShift & %s:: {"):format(a.hotkey)
        out[#out + 1] = ("    ActivateOrRun(\"%s\", \"%s\", \"%s\")"):format(title, aumid, exe)
        out[#out + 1] = ("    EnsureWindow(\"%s\")"):format(title)
        out[#out + 1] = "}"
      else
        out[#out + 1] = ("RShift & %s::ActivateOrRun(\"%s\", \"%s\", \"%s\")")
          :format(a.hotkey, title, aumid, exe)
      end
    end
  end

elseif mode == "casks" then
  for _, a in ipairs(apps) do
    if a.brew_cask then out[#out + 1] = a.brew_cask end
  end

elseif mode == "winget" then
  for _, a in ipairs(apps) do
    if a.winget_id then out[#out + 1] = a.winget_id end
  end

else
  io.stderr:write("usage: gen.lua {skhd|ahk|casks|winget}\n")
  os.exit(1)
end

io.write(table.concat(out, "\n") .. "\n")
