#!/bin/bash

# Write a sorted snapshot of installed Homebrew package versions to
# Brewfile.snapshot. This is a MANUAL diff artifact: commit it deliberately to
# review what changed between two machines or two dates.
#
# Deliberately NOT wired into CI (Homebrew doesn't pin versions, so a diff gate
# would be pure noise) and NOT auto-committed (it captures your full machine
# state — review before committing to a PUBLIC repo).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$SCRIPT_DIR/Brewfile.snapshot"

if ! command -v brew >/dev/null 2>&1; then
  echo "brew not found on PATH" >&2
  exit 1
fi

{
  echo "# Homebrew package snapshot — generated by scripts/snapshot.sh"
  echo "# Review before committing; this reflects the whole machine, not just the Brewfile."
  echo ""
  echo "# Formulae"
  brew list --versions --formula | sort
  echo ""
  echo "# Casks"
  brew list --versions --cask | sort
} > "$OUT"

echo "Wrote $OUT"
